// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdDKg5NwtYiTv995lC-g0pxuKxS7qP8M',
    appId: '1:743552243419:web:b5899accec13be5f04defe',
    messagingSenderId: '743552243419',
    projectId: 'loqme-53f23',
    authDomain: 'loqme-53f23.firebaseapp.com',
    storageBucket: 'loqme-53f23.firebasestorage.app',
    measurementId: 'G-ZNNLR48PR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPkr-4sM8BBpVtQqWlj-2_cJJpIbeHVy0',
    appId: '1:743552243419:android:a7ce55a09b64158504defe',
    messagingSenderId: '743552243419',
    projectId: 'loqme-53f23',
    storageBucket: 'loqme-53f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmruDhGVULm_A8BD-LRiErnWNGvuvnpU',
    appId: '1:743552243419:ios:04a89c71e4b604bc04defe',
    messagingSenderId: '743552243419',
    projectId: 'loqme-53f23',
    storageBucket: 'loqme-53f23.firebasestorage.app',
    iosBundleId: 'ir.loqmeapp.application',
  );
}
